services:
  - type: web
    name: meme-server
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: UNSPLASH_ACCESS_KEY
        sync: false